A = csvread('Zeroestable.csv');
h = zeros(6,1);
null = zeros(length(A(:,1)),1);
degree = 3*A(:,1) + 3;
h(1) = plot(nan,nan,'r-'); hold on;
h(2) = plot(nan,nan,'b-'); 
h(3) = plot(nan,nan,'ko');
h(4) = plot(nan,nan,'ks');
h(5) = plot(nan,nan,'kx');
h(6) = plot(nan,nan,'k-');
plot(A(:,1),A(:,2),'bo-');
plot(A(:,1),A(:,3),'bs-');
plot(A(:,1),A(:,4),'bx-');
plot(A(:,1),A(:,5),'ro-');
plot(A(:,1),A(:,6),'rs-');
plot(A(:,1),A(:,7),'rx-'); 
plot(A(:,1),degree, 'k'); hold off;
l = legend(h,'Legendre','Sobolev','Bottom Edge','Side Edges','Total','3$d$ + 3');
%set(gca,'defaulttextinterpreter','latex');  
set(gca,'FontSize',20);
set(gca, 'TickLabelInterpreter','latex');  
set(l, 'Interpreter','latex');
xlabel('degree ($d$)');
ylabel('Number of Zeros');